compiler:
  solc:
    version: 0.8.4
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.0.0"
      - "@ozUpgradesV4=OpenZeppelin/openzeppelin-contracts-upgradeable@4.0.0"
      - "@uniswap/v3-core=Uniswap/uniswap-v3-core@1.0.0"
      - "@uniswap/v3-periphery=Uniswap/uniswap-v3-periphery@1.0.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.1"
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.0.0
  - Uniswap/uniswap-v3-core@1.0.0
  - Uniswap/uniswap-v3-periphery@1.0.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.0.0